export const campaignContractAbi = [
  {
    type: "function",
    name: "FLOW_VERSION",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "event",
    name: "DonationReceived",
    inputs: [
      { indexed: true, name: "campaignKey", type: "bytes32" },
      { indexed: true, name: "donor", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "totalRaised", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "MilestoneProofSubmitted",
    inputs: [
      { indexed: true, name: "milestoneIndex", type: "uint256" },
      { indexed: false, name: "proofCID", type: "string" },
    ],
  },
  {
    type: "event",
    name: "MilestoneStatusChanged",
    inputs: [
      { indexed: true, name: "milestoneIndex", type: "uint256" },
      { indexed: false, name: "status", type: "uint8" },
    ],
  },
  {
    type: "event",
    name: "FundsReleased",
    inputs: [
      { indexed: true, name: "milestoneIndex", type: "uint256" },
      { indexed: true, name: "shelter", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "RefundClaimed",
    inputs: [
      { indexed: true, name: "donor", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "donate",
    stateMutability: "payable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "submitMilestoneProof",
    stateMutability: "nonpayable",
    inputs: [
      { name: "milestoneIndex", type: "uint256" },
      { name: "proofCID", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "approveMilestone",
    stateMutability: "nonpayable",
    inputs: [{ name: "milestoneIndex", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "rejectMilestone",
    stateMutability: "nonpayable",
    inputs: [{ name: "milestoneIndex", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawMilestone",
    stateMutability: "nonpayable",
    inputs: [{ name: "milestoneIndex", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelCampaign",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "finalizeExpired",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "claimRefund",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "getRefundableAmount",
    stateMutability: "view",
    inputs: [{ name: "donor", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "refundClaimed",
    stateMutability: "view",
    inputs: [{ name: "donor", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "campaignStatus",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "currentMilestoneIndex",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getMilestone",
    stateMutability: "view",
    inputs: [{ name: "milestoneIndex", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "percentageBps", type: "uint16" },
          { name: "allocation", type: "uint256" },
          { name: "cumulativeThreshold", type: "uint256" },
          { name: "status", type: "uint8" },
          { name: "proofCID", type: "string" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "goal",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "deadline",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalRaised",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "currentMilestoneIndex",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;
